name: Mi Workflow

on: push

jobs:
  tareas:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      
    steps:
      - name: Analizar Código (python lint)
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
