name: MI Work

on: push

jobs:
  tareas:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: bajar codigo
        uses: actions/checkout@v4

      - name: analizar codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
    
